
INSERT INTO products (name, slug, description, price, stock, category_id, season, size_options, images, is_active) VALUES
('Jean Skinny Taille Haute', 'jean-skinny-taille-haute', 'Jean skinny en denim indigo foncé, coupe ajustée et taille haute pour une silhouette élancée. Tissu stretch confortable.', 89.90, 25, '93bdb357-9b9a-404f-8690-9d47d654dd38', 'all_season', '["S","M","L","XL"]', ARRAY['/products/high-waisted-skinny-jeans-1.jpg'], true),
('Top Crop Blanc Manches Bouffantes', 'top-crop-blanc-manches-bouffantes', 'Top crop élégant en coton blanc avec manches bouffantes. Parfait pour un look estival chic.', 45.00, 30, '97161295-e558-4827-a7a8-c385eb3f2a66', 'summer', '["S","M","L"]', ARRAY['/products/white-cropped-top-1.jpg'], true),
('Pantalon Palazzo Noir', 'pantalon-palazzo-noir', 'Pantalon palazzo fluide en noir, coupe large et taille haute. Élégance et confort au quotidien.', 75.00, 20, NULL, 'all_season', '["S","M","L","XL"]', ARRAY['/products/wide-leg-palazzo-1.jpg'], true),
('Robe Midi Fleurie Été', 'robe-midi-fleurie-ete', 'Robe midi à imprimé floral délicat, tissu léger et fluide. Idéale pour les journées ensoleillées.', 95.00, 15, NULL, 'summer', '["S","M","L","XL"]', ARRAY['/products/floral-summer-dress-1.jpg'], true),
('Pull Col Roulé Côtelé Camel', 'pull-col-roule-cotele-camel', 'Pull col roulé en maille côtelée, coloris camel chaleureux. Doux et confortable pour l''hiver.', 69.90, 22, '97161295-e558-4827-a7a8-c385eb3f2a66', 'winter', '["S","M","L","XL"]', ARRAY['/products/ribbed-turtleneck-1.jpg'], true),
('Jean Boyfriend Déchiré', 'jean-boyfriend-dechire', 'Jean boyfriend décontracté en denim bleu clair avec déchirures aux genoux. Style casual et tendance.', 79.90, 18, '93bdb357-9b9a-404f-8690-9d47d654dd38', 'all_season', '["S","M","L","XL"]', ARRAY['/products/boyfriend-jeans-1.jpg'], true),
('Caraco Satin Rose Poudré', 'caraco-satin-rose-poudre', 'Caraco en satin luxueux, coloris rose poudré. Fines bretelles et coupe fluide pour un look raffiné.', 39.90, 35, '97161295-e558-4827-a7a8-c385eb3f2a66', 'summer', '["S","M","L"]', ARRAY['/products/satin-camisole-1.jpg'], true);
